id: AEB027F2E
title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from the Extremely
  Secret Assembly of Sugatas)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:22:00.253383
  last_modified_at: 2022-02-28 23:22:00.253406
